package com.bank.bian.tradeservicescustomerdirectory;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Trade Services Customer Directory
 *
 * Business Area:      Operations and Execution
 * Business Domain:    Trade Banking
 * Functional Pattern: Catalog
 * Asset Type:         Trade Counterparty
 * Control Record:     Trade Counterparty Directory Entry
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Trade Services Customer Directory — BIAN Semantic API")
                .description("Service Domain 'Trade Services Customer Directory' (Catalog pattern) "
                        + "operating on the 'Trade Counterparty Directory Entry' control record.")
                .version("0.1.0"));
    }
}
